version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.8
  
  pre_build:
    commands:
      - mkdir prueba_git
      - aws s3 cp s3://chapinbet-smartplay-build/prueba_git/ ./prueba_git --recursive
  
  build:
    commands:
      - cd prueba_git
      - python main.py

artifacts:
  files:
    - '**/*'