version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.8
  
  pre_build:
    commands:
      - aws s3 cp s3://chapinbet-smartplay-build/prueba_git/ . --recursive
  
  build:
    commands:
      - python -m compileall main.py

artifacts:
  files:
    - '**/*'